### ISSUE TITLE
Struggling to install

### ISSUE THREAD

**Issue by joepagan** [thisismyjam/jam-image-filter#2]
Hey peeps,
I'm attempting to install this (yes I'm a python noob).
Looks like PIL isn't working for me, but you can user PILLOW instead if you modify the requirements.txt

But my problem is as follows, I'm trying to install with the following line:
    sudo pip install -r requirements.txt --allow-all-external

But the error I get is:
    Running setup.py (path:/Users/username/Documents/sites/test/public_html/jam_image_filter/src/aggdraw/setup.py) egg_info for package aggdraw
      Traceback (most recent call last):
        File "<string>", line 17, in <module>
        File "/Users/username/Documents/sites/test/public_html/jam_image_filter/src/aggdraw/setup.py", line 35
          print "===", "freetype not available (edit setup.py to enable)"
                    ^
      SyntaxError: invalid syntax
      Complete output from command python setup.py egg_info:
      Traceback (most recent call last):

File "<string>", line 17, in <module>

File "/Users/username/Documents/sites/test/public_html/jam_image_filter/src/aggdraw/setup.py", line 35

print "===", "freetype not available (edit setup.py to enable)"

^

  SyntaxError: invalid syntax

**Comment by andreasjansson** [comment]
Hi @lexbi, which version of Python are you using? You probably need to be on 2.7 for this to work. Also, I think aggdraw needs freetype, so you might have to do `brew install freetype` or something like that.

HTH, let us know if you still have issues

**Comment by joepagan** [comment]
Wow quick response!

I'm trying on both 2.7.6 & 3.4.0b2
turns out I have freetype installed (2.5.2)

**Comment by andreasjansson** [comment]
What happens if you just do `pip install -e git+https://github.com/jakul/aggdraw.git#egg=aggdraw`?

**Comment by joepagan** [comment]
I get the same error as above, I think it doesn't have a problem with anything else (so far) in requirements.txt

**Comment by andreasjansson** [comment]
Weird, that looks a lot like a Python 3 error. What does `pip --version` say?

**Comment by joepagan** [comment]
Might have something to do with it!
    pip 1.5.4 from /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (python 3.4)

I thought you had to user "pip3 install" to use that one. how would I set this to use pip from my 2.7.6 install?

**Comment by andreasjansson** [comment]
I'm not a Mac user so might not be the best person for this, but maybe this helps? http://stackoverflow.com/questions/6998545/how-can-i-make-python-2-6-my-default-in-mac-os-x-lion Instead of 2.6 you probably want to default to 2.7

**Comment by joepagan** [comment]
Ok thanks for that Andreas, appreciate it! I'll give it a shot and let you know how it goes!

**Comment by joepagan** [comment]
Ok so now I appear to have pip running on 2.7 `pip --version` gives me: `pip 1.5.4 from /Library/Python/2.7/site-packages (python 2.7)`

Now when I run `sudo pip install -e git+https://github.com/jakul/aggdraw.git#egg=aggdraw`

I get this:
`Obtaining aggdraw from git+https://github.com/jakul/aggdraw.git#egg=aggdraw
Updating ./src/aggdraw clone
Running setup.py (path:/Users/username/src/aggdraw/setup.py) egg_info for package aggdraw
Installing extra requirements: 'egg'
Installing collected packages: aggdraw
Running setup.py develop for aggdraw
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
building 'aggdraw' extension
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -DHAVE_FREETYPE2 -Iagg2/include -Iagg2/font_freetype -I/usr/include -I/usr/include/freetype2 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c aggdraw.cxx -o build/temp.macosx-10.9-intel-2.7/aggdraw.o
clang: error: unknown argument: '-mno-fused-madd' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
error: command 'cc' failed with exit status 1
Complete output from command /usr/bin/python -c "import setuptools, tokenize; __file__='/Users/username/src/aggdraw/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
running develop
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running egg_info
writing aggdraw.egg-info/PKG-INFO
writing top-level names to aggdraw.egg-info/top_level.txt
writing dependency_links to aggdraw.egg-info/dependency_links.txt
warning: manifest_maker: standard file '-c' not found
reading manifest file 'aggdraw.egg-info/SOURCES.txt'
writing manifest file 'aggdraw.egg-info/SOURCES.txt'
running build_ext
building 'aggdraw' extension
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -DHAVE_FREETYPE2 -Iagg2/include -Iagg2/font_freetype -I/usr/include -I/usr/include/freetype2 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c aggdraw.cxx -o build/temp.macosx-10.9-intel-2.7/aggdraw.o
clang: error: unknown argument: '-mno-fused-madd' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
error: command 'cc' failed with exit status 1
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize; __file__='/Users/username/src/aggdraw/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps failed with error code 1 in /Users/username/src/aggdraw
Storing debug log for failure in /Users/username/Library/Logs/pip.log`

**Comment by joepagan** [comment]
Just to give you a heads up so you're not looking in the wrong place (still needs more research), looks like its an issue with Apple, they recently updated XCode (which shell uses some stuff on OSX).

I recently tried to install the setup.py with this `sudo easy_install /Users/username/Documents/sites/test/public_html/jam_image_filter/src/aggdraw/`

But you end up getting this error:
`clang: error: unknown argument: '-mno-fused-madd' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future`

There seems to be plenty of references to it on various stackoverflow links, though I'm yet to find a solution that works:
http://stackoverflow.com/questions/22313407/clang-error-unknown-argument-mno-fused-madd-python-package-installation-fa
http://stackoverflow.com/questions/22390655/ansible-installation-clang-error-unknown-argument-mno-fused-madd

**Comment by andreasjansson** [comment]
Oh dear, that looks pretty messy. Let us know how you get on, maybe we need to update the documentation to mention this issue.

**Comment by joepagan** [comment]
Will let you know as soon as I do! Will commit something if need be!

**Comment by joepagan** [comment]
Looks like aggdraw is trying to use relative paths to freetype (where there is no install of freetype), not really sure if I can set a global variable for that, or just install freetype to the directory that it desires.
Changing all the paths manually in their files is getting annoying will have to look later today.

**Comment by joepagan** [comment]
Ok so I moved all the files from `/usr/local/Cellar/freetype/2.5.3_1/include/freetype2` 
Put it in the folder `/Users/username/Downloads/aggdraw-master/agg2/font_freetype`
Then to install it on OSX `sudo ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future easy_install /Users/username/Downloads/aggdraw-master`

Problem is now that when I try to invoke like in your example. PILLOW doesn't seem to have "Image" installed:
`python leaves.py /Users/username/Documents/sites/test/public_html/files/5913/9509/0669/unkle_17-03-2014_2111__351.jpg /Users/username/Documents/sites/test/public_html/files/5913/9509/0669/unkle_17-03-2014_2111__351-test.jpg`

Gives me:
`Traceback (most recent call last):
  File "leaves.py", line 4, in <module>
    import Image
ImportError: No module named Image`

Will investigate this later.

**Comment by andreasjansson** [comment]
Thanks, sorry I didn't have time to look at this yesterday. In fact, the
next couple of days are also crazy busy for me. I was worried PILLOW
wouldn't be exactly compatible with PIL. Is there specific functionality in
PILLOW that makes it worth migrating over? Or is PIL completely dead? I'm
in the "if it's not broken don't fix it" camp most of the time, but at the
same time, if there's unmaintained code in there, it'll probably come back
and bite us in the future when other software gets updated.

**Comment by joepagan** [comment]
I think I may have jumped the gun on PIL/PILLOW. PIL May still be available on yum and other download packages, I'm using pip/brew on OSX, it appears PIL on pip is dead. Don't worry about it it's not your fault. I might be able to download this "Image" module separately though I'll take a look when I have more time this eve.

**Comment by joepagan** [comment]
Woooohoooo, just got it going, turns out PILLOW needs requires slightly different method of importing modules. So I just installed an old version of PIL manually (unfortunately you can't get through pip/brew anymore. So download a version here:
http://www.pythonware.com/products/pil/

Download the file, navigate to the dir then when in the folder `python setup.py install`

I also then had to install "scipy" through brew, though you first need to install "nose", `pip install nose` (you might need sudo) then `brew install scipy`.

Though as I mentioned in a previous post, when attempting to install PIL it was moaning about freetype. So you've just got to copy this folder `/usr/local/Cellar/freetype/2.5.3_1/include/freetype2` and copy it to `/Users/username/Downloads/Imaging-1.1.7` then rename the folder to `freetype`
